services: docker
language: bash

script:
    - SCRIPT=build_test_push_notify.sh
    - curl -O https://raw.githubusercontent.com/cyber-dojo-languages/image_builder/master/${SCRIPT}
    - chmod 700 ./${SCRIPT}
    - travis_retry ./${SCRIPT}
    - ./check_version.sh
