version: 2
jobs:
  build-publish-trigger:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build image, test it, push it dockerhub, notify dependents
          command: ./pipe_build_up_test.sh

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: [ master ]
    jobs:
      - build-publish-trigger:
          context: cyberdojo-languages-context
          filters:
            branches:
              only: [ master ]
  commit:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-languages-context
          filters:
            branches:
              only: [ master ]
